# Description
# ===========
# This playbook will delete an Azure VM 

- name: Delete Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: abcdefg
    vm_name: testvm
    location: eastus
  tasks:
  - name: delete all auto create resource
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      state: absent
